[env]
TERM = "xterm-256color"

[general]
import = [
    "~/.config/alacritty/themes/themes/kanagawa_dragon.toml"
]

[window]
decorations = "none"
opacity = 0.8
blur = false
padding = { x = 12, y = 12 }
dynamic_padding = true
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 10
offset = { x = 0, y = 1 }

[cursor]
style = { shape = "Block", blinking = "On" }
blink_timeout = 0
unfocused_hollow = true

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true

